# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        htpasswd:
            id: htpasswd_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        nain:
            anonymous: ~
            http_basic: ~
            simple_form:
                login_path: /login
                check_path: /login_check
                csrf_provider: security.csrf.token_manager
                authenticator: htpasswd_authenticator
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secure, roles: ROLE_USER }
